
networks:
  traefik_proxy:
    external: true
  cloudflare-transport:

include:
  - ./traefik/traefik.yaml
  - ./portainer/portainer.yaml
  - ./grafana/grafana.yaml
  - ./watchtower/watchtower.yaml
  - ./prometheus/prometheus.yaml
  - ./pihole/pihole.yaml
  - ./mealie/mealie.yaml
  - ./cloudflared/cloudflared.yaml
  # NZB
  - ./nzb/sonarr/sonarr.yaml
  - ./nzb/radarr/radarr.yaml
  - ./nzb/hydra2/hydra.yaml
  - ./nzb/sabnzbd/sabnzbd.yaml

  - ./jellyfin/docker-compose.yaml







