
networks:
  traefik_proxy:
    external: true

include:
  - ./traefik/docker-compose.yaml
  - ./portainer/docker-compose.yaml
  - ./grafana/docker-compose.yaml
  - ./watchtower/docker-compose.yaml
  - ./prometheus/docker-compose.yaml
  - ./pihole/docker-compose.yaml
  - ./mealie/docker-compose.yaml





