
networks:
  traefik_proxy:
    external: true
  cloudflare-transport:

include:
  - ./traefik/traefik.yaml
  - ./portainer/portainer.yaml
  - ./grafana/grafana.yaml
  - ./watchtower/watchtower.yaml
  - ./prometheus/prometheus.yaml
  - ./pihole/pihole.yaml
  - ./mealie/mealie.yaml
  - ./cloudflared/cloudflared.yaml
  # NZB
  - ./media-services/sonarr/sonarr.yaml
  - ./media-services/radarr/radarr.yaml
  - ./media-services/hydra2/hydra.yaml
  - ./media-services/sabnzbd/sabnzbd.yaml

  #- ./jellyfin/docker-compose.yaml

# Experimental
  - ./ollama/ollama.yaml






