version: '3'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    domainname: ${DOMAIN}
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '67:67/udp'
      # - "443:443"
      - '8053:80/tcp'
    labels:
      - 'traefik.enable=true'
      - 'traefik.frontend.rule=HostRegexp:pihole.${DOMAIN},{catchall:.*}'
      - 'traefik.frontend.priority=1'
      - 'traefik.backend=pihole'
      - 'traefik.port=80'
      - 'traefik.docker.network=traefik_proxy'
    volumes:
      - ${PIHOLE_LOG}:/var/log/pihole.log
      - ${PIHOLE_DNSMASQ}:/etc/dnsmasq.d
      - ${PIHOLE_ETC}:/etc/pihole
    networks:
      - traefik_proxy
    cap_add:
      - NET_ADMIN
    environment:
      ServerIP: ${SERVERIP}
      PROXY_LOCATION: pihole
      WEBPASSWORD: ${PIHOLE_PASSWORD}
      TZ: ${TZ}
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
      VIRTUAL_HOST: pihole
    extra_hosts:
      # LAN hostnames for other docker containers using reverse proxy
      - 'plex plex.${DOMAIN}:${SERVERIP}'
      - 'radarr radarr.${DOMAIN}:${SERVERIP}'
      - 'sonarr sonarr.${DOMAIN}:${SERVERIP}'
      - 'sabnzbd sabnzbd.${DOMAIN}:${SERVERIP}'
      - 'pihole pihole.${DOMAIN}:${SERVERIP}'
    restart: unless-stopped
networks:
  traefik_proxy:
    external: true
