
services:
  traefik:
    image: traefik:latest
    hostname: traefik
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik_proxy
      - cloudflare-transport
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    # healthcheck:
    #   test: ["CMD", "traefik", "healthcheck", "--ping"]
    #   interval: 30s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s
    environment:
      - TZ=${TZ}
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_API_KEY=${CF_API_KEY}
    command:
      - '--docker.domain=${DOMAIN}'
      - '--logLevel=${TRAEFIK_LOG_LEVEL}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/traefik.yml:ro
      - ./config/config.yml:/config.yml:ro
      - ./config/acme.json:/acme.json
      - ${DOCKERDIR}/logs/${HOSTNAME}/traefik:/logs # Traefik logs
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)'
      - 'traefik.http.routers.traefik.entrypoints=https'
      - 'traefik.http.routers.traefik.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.traefik.tls.domains[0].main=${DOMAIN}'
      - 'traefik.http.routers.traefik.tls.domains[0].sans=*.${DOMAIN}'
      - 'traefik.http.services.traefik.loadbalancer.server.port=8080'
      - 'traefik.docker.network=traefik_proxy'
      # - "traefik.http.routers.pingweb.rule=PathPrefix(`/ping`)"
      # - "traefik.http.routers.pingweb.service=ping@internal"
      # - "traefik.http.routers.pingweb.entrypoints=websecure"
    restart: unless-stopped

networks:
  traefik_proxy:
    external: true
  cloudflare-transport: