api:
  insecure: true
  dashboard: true
  debug: true

entryPoints:
  http:
    address: ':80'
  # https:
  #   address: ':443'

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false

#certificatesResolvers:
#  cloudflare:
#    acme:
#      email: your@email.com
#      storage: acme.json
#      dnsChallenge:
#        provider: cloudflare
#        resolvers:
#          - "1.1.1.1:53"
#          - "1.0.0.1:53"

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
