services:

  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/provisioning/:/etc/grafana/provisioning/
    networks:
      - traefik_proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.grafana.rule=Host(`grafana.${DOMAIN}`)'
      - 'traefik.http.routers.grafana.entrypoints=https'
      - 'traefik.http.routers.grafana.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.grafana.tls.domains[0].main=${DOMAIN}'
      - 'traefik.http.routers.grafana.tls.domains[0].sans=*.${DOMAIN}'
      - 'traefik.http.services.grafana.loadbalancer.server.port=3000'
      - 'traefik.docker.network=traefik_proxy'
    restart: unless-stopped