services:

  watchtower:
      container_name: watchtower
      restart: always
      image: containrrr/watchtower
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      command: --schedule "0 0 23 * * MON" --cleanup