version: '3'

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - "${CONFIG_VOLUME}/plex:/config"
      - "${MEDIA_VOLUME}/tv:/data/tv"
      - "${MEDIA_VOLUME}/movies:/data/movies"
      - "${PLEX_TRANSCODE}:/transcode"
    network_mode: host
    environment:
      PLEX_CLAIM: claim-${PLEX_CLAIM}
      ADVERTISE_IP: http://${SERVERIP}:32400/
      HOTNAME: antman
      PLEX_UID: ${UID}
      PLEX_GUID: ${GUID}      
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=plex"
      - "traefik.frontend.rule=Host:plex.${DOMAINNAME}"
      - "traefik.port=32400"
      - "traefik.protocol=http"
      - "traefik.docker.network=traefik_proxy"
    restart: unless-stopped

  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    volumes:
      - "${CONFIG_VOLUME}/sabnzbd:/config"
      - '${DOWNLOAD_VOLUME}/complete:/downloads'
      - '${DOWNLOAD_VOLUME}/incomplete:/incomplete-downloads'
    ports:
      - 8081:8080
    environment:
      PUID: ${UID}
      PGID: ${GUID}
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sabnzbd"
      - "traefik.frontend.rule=Host:sabnzbd.${DOMAINNAME}"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - "${CONFIG_VOLUME}/radarr:/config"
      - "${DOWNLOAD_VOLUME}/complete:/downloads"
      - "${MEDIA_VOLUME}/movies:/movies"
    environment:
      PUID: ${UID}
      PGID: ${GUID}
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=radarr"
      - "traefik.frontend.rule=Host:radarr.${DOMAINNAME}"      
      - "traefik.port=7878"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:preview
    container_name: sonarr
    depends_on:
      - sabnzbd
      - plex
    volumes:
      - "${CONFIG_VOLUME}/sonarr:/config"
      - "${DOWNLOAD_VOLUME}/complete:/downloads"
      - "${MEDIA_VOLUME}/tv:/tv"
    environment:
      PUID: ${UID}
      PGID: ${GUID}
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sonarr"
      - "traefik.frontend.rule=Host:sonarr.${DOMAINNAME}"
      - "traefik.port=8989"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy
    restart: unless-stopped

  nzbhydra:
    image: linuxserver/hydra
    container_name: nzbhydra
    volumes:
      - "${CONFIG_VOLUME}/nzbhydra:/config"
      - "${DOWNLOAD_VOLUME}:/downloads"
    environment:
      PUID: ${UID}
      PGID: ${GUID}
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nzbhydra"
      - "traefik.frontend.rule=Host:hydra.${DOMAINNAME}"
      - "traefik.port=5075"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy
    restart: unless-stopped
  
  tautulli:
    image: linuxserver/tautulli
    container_name: plexpy
    volumes: 
      - ${CONFIG_VOLUME}/tautulli/config:/config
      - ${CONFIG_VOLUME}/tautulli/logs:/logs:ro
    environment: 
      PUID: ${UID}
      PGID: ${GUID}
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=plexpy"
      - "traefik.frontend.rule=Host:plexpy.${DOMAINNAME}"
      - "traefik.port=8181"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy
    restart: unless-stopped

  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    volumes: 
      - "${CONFIG_VOLUME}/lazylibrarian/config:/config"
      - "${DOWNLOAD_VOLUME}/complete:/downloads"
      - "${MEDIA_VOLUME}/books:/books"
    environment: 
      PUID: ${UID}
      PGID: ${GUID}
      TZ: ${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=lazylibrarian"
      - "traefik.frontend.rule=Host:librarian.${DOMAINNAME}"
      - "traefik.port=5299"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy
    restart: unless-stopped

networks:
    traefik_proxy:
      external: true
