version: '3'

services:
  portainer:
    image: portainer/portainer-ce
    hostname: portainer
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - traefik_proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)'
      - 'traefik.http.routers.portainer.entrypoints=https'
      - 'traefik.http.routers.portainer.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.portainer.tls.domains[0].main=${DOMAIN}'
      - 'traefik.http.routers.portainer.tls.domains[0].sans=*.${DOMAIN}'
      - 'traefik.http.services.portainer.loadbalancer.server.port=9000'
      - 'traefik.docker.network=traefik_proxy'
    restart: unless-stopped